CREATE TABLE book_genre(product_id INT NOT NULL REFERENCES book, genre VARCHAR(80) NOT NULL, PRIMARY KEY(product_id, genre));
INSERT INTO book_genre(product_id, genre) VALUES (1, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (1, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (2, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (3, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (3, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (3, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (4, 'Gothic');
INSERT INTO book_genre(product_id, genre) VALUES (4, 'Bildungsroman');
INSERT INTO book_genre(product_id, genre) VALUES (5, 'Tragedy');
INSERT INTO book_genre(product_id, genre) VALUES (6, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (6, 'Realistic Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (7, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (8, 'Realistic Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (8, 'Bildungsroman');
INSERT INTO book_genre(product_id, genre) VALUES (9, 'Mystery');
INSERT INTO book_genre(product_id, genre) VALUES (9, 'Thriller');
INSERT INTO book_genre(product_id, genre) VALUES (10, 'Classics');
INSERT INTO book_genre(product_id, genre) VALUES (10, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (11, 'Historical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (11, 'Drama');
INSERT INTO book_genre(product_id, genre) VALUES (12, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (12, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (12, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (13, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (14, 'Political Satire');
INSERT INTO book_genre(product_id, genre) VALUES (15, 'Autobiography');
INSERT INTO book_genre(product_id, genre) VALUES (16, 'Crime');
INSERT INTO book_genre(product_id, genre) VALUES (16, 'Mystery');
INSERT INTO book_genre(product_id, genre) VALUES (17, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (17, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (18, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (19, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (20, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (20, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (21, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (22, 'Mystery');
INSERT INTO book_genre(product_id, genre) VALUES (23, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (24, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (25, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (26, 'Mystery');
INSERT INTO book_genre(product_id, genre) VALUES (27, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (28, 'Allegory');
INSERT INTO book_genre(product_id, genre) VALUES (29, 'Tragedy');
INSERT INTO book_genre(product_id, genre) VALUES (30, 'Thriller');
INSERT INTO book_genre(product_id, genre) VALUES (31, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (31, 'Drama');
INSERT INTO book_genre(product_id, genre) VALUES (32, 'Novella');
INSERT INTO book_genre(product_id, genre) VALUES (32, 'Tragedy');
INSERT INTO book_genre(product_id, genre) VALUES (33, 'Historical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (34, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (35, 'Adventure');
INSERT INTO book_genre(product_id, genre) VALUES (35, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (36, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (36, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (36, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (37, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (37, 'Christian Literature');
INSERT INTO book_genre(product_id, genre) VALUES (38, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (38, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (39, 'Political Novel');
INSERT INTO book_genre(product_id, genre) VALUES (39, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (40, 'Memoir');
INSERT INTO book_genre(product_id, genre) VALUES (41, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (41, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (42, 'Bildungsroman');
INSERT INTO book_genre(product_id, genre) VALUES (43, 'Victorian Literature');
INSERT INTO book_genre(product_id, genre) VALUES (44, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (45, 'Philosophical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (46, 'Historical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (46, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (47, 'Historical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (48, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (49, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (49, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (50, 'Poetry');
INSERT INTO book_genre(product_id, genre) VALUES (51, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (51, 'Adventure');
INSERT INTO book_genre(product_id, genre) VALUES (52, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (52, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (52, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (53, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (53, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (53, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (53, 'Bildungsroman');
INSERT INTO book_genre(product_id, genre) VALUES (54, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (55, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (55, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (56, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (56, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (57, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (58, 'Picaresque Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (59, 'Children''s Literature');
INSERT INTO book_genre(product_id, genre) VALUES (60, 'Mystery');
INSERT INTO book_genre(product_id, genre) VALUES (61, 'Thriller');
INSERT INTO book_genre(product_id, genre) VALUES (62, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (62, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (63, 'Tragedy');
INSERT INTO book_genre(product_id, genre) VALUES (63, 'Gothic');
INSERT INTO book_genre(product_id, genre) VALUES (64, 'Domestic Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (65, 'Satire');
INSERT INTO book_genre(product_id, genre) VALUES (65, 'Dark Comedy');
INSERT INTO book_genre(product_id, genre) VALUES (66, 'Historical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (67, 'Domestic Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (68, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (69, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (69, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (69, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (69, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (70, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (71, 'Gothic');
INSERT INTO book_genre(product_id, genre) VALUES (71, 'Horror');
INSERT INTO book_genre(product_id, genre) VALUES (71, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (72, 'Gothic');
INSERT INTO book_genre(product_id, genre) VALUES (72, 'Horror');
INSERT INTO book_genre(product_id, genre) VALUES (73, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (73, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (73, 'Thriller');
INSERT INTO book_genre(product_id, genre) VALUES (73, 'Dystopia');
INSERT INTO book_genre(product_id, genre) VALUES (74, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (75, 'Comedy');
INSERT INTO book_genre(product_id, genre) VALUES (76, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (77, 'Adventure');
INSERT INTO book_genre(product_id, genre) VALUES (78, 'Comedy');
INSERT INTO book_genre(product_id, genre) VALUES (78, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (79, 'Poetry');
INSERT INTO book_genre(product_id, genre) VALUES (80, 'Novella');
INSERT INTO book_genre(product_id, genre) VALUES (80, 'Children''s Literature');
INSERT INTO book_genre(product_id, genre) VALUES (81, 'Memoir');
INSERT INTO book_genre(product_id, genre) VALUES (82, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (83, 'Historical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (84, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (85, 'Children''s Literature');
INSERT INTO book_genre(product_id, genre) VALUES (86, 'Thriller');
INSERT INTO book_genre(product_id, genre) VALUES (87, 'Memoir');
INSERT INTO book_genre(product_id, genre) VALUES (87, 'Autobiography');
INSERT INTO book_genre(product_id, genre) VALUES (88, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (88, 'Mystery');
INSERT INTO book_genre(product_id, genre) VALUES (89, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (89, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (90, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (91, 'Young Adult Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (91, 'Science Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (91, 'Post-Apocalyptic');
INSERT INTO book_genre(product_id, genre) VALUES (92, 'Non-Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (93, 'Children''s Literature');
INSERT INTO book_genre(product_id, genre) VALUES (94, 'Fantasy');
INSERT INTO book_genre(product_id, genre) VALUES (95, 'Philosophical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (96, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (97, 'Horror');
INSERT INTO book_genre(product_id, genre) VALUES (97, 'Gothic');
INSERT INTO book_genre(product_id, genre) VALUES (98, 'Crime');
INSERT INTO book_genre(product_id, genre) VALUES (98, 'Mystery');
INSERT INTO book_genre(product_id, genre) VALUES (98, 'Thriller');
INSERT INTO book_genre(product_id, genre) VALUES (99, 'Romance');
INSERT INTO book_genre(product_id, genre) VALUES (100, 'Historical Fiction');
INSERT INTO book_genre(product_id, genre) VALUES (100, 'Domestic Fiction');
