CREATE TABLE publishes(product_id INT PRIMARY KEY REFERENCES product, publisher_name VARCHAR(80) REFERENCES publisher(name), year_published SMALLINT, reorder_threshold INT, commission_percent NUMERIC(5, 3));
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (1, 'Scholastic', 2008, -1, 49.24);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (2, 'Bloomsbury', 1997, 75, 47.25);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (3, 'Little, Brown and Company', 2005, 50, 70.89);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (4, 'J. B. Lippincott & Co.', 1960, 500, 29.41);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (5, 'Charles Scribner''s Sons', 1925, 25, 25.13);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (6, 'Dutton Books', 2012, -1, 61.29);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (7, 'George Allen & Unwin', 1937, 100, 54.98);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (8, 'Little, Brown and Company', 1951, -1, 37.79);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (9, 'Pocket Books', 2000, 50, 73.94);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (10, 'Bloomsbury', 1813, 25, 44.38);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (11, 'Riverhead Books', 2003, 500, 68.82);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (12, 'Katherine Tegen Books', 2011, 250, 51.25);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (13, 'Secker & Warburg', 1949, 1000, 41.44);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (14, 'Secker & Warburg', 1945, 250, 24.64);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (15, 'Contact Publishing', 1947, -1, 57.13);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (16, 'Norstedts Förlag', 2005, 75, 34.5);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (17, 'Scholastic', 2009, 25, 23.44);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (18, 'Bloomsbury', 1999, 75, 45.82);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (19, 'George Allen & Unwin', 1954, 50, 53.27);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (20, 'Scholastic', 2010, 500, 54.11);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (21, 'Bloomsbury', 2003, 250, 49.47);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (22, 'Little, Brown and Company', 2002, 500, 53.77);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (23, 'Bloomsbury', 1998, 75, 25.83);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (24, 'Bloomsbury', 2000, 75, 62.62);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (25, 'Bloomsbury', 2007, 500, 36.72);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (26, 'Doubleday', 2003, 100, 39.15);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (27, 'Bloomsbury', 2005, 250, 40.63);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (28, 'Faber and Faber', 1954, 500, 41.89);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (29, 'Prentice Hall', 1595, 25, 64.3);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (30, 'Crown Publishing Group', 2012, 1000, 74.33);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (31, 'Penguin Books', 2009, 500, 64.07);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (32, 'Covici Friede', 1937, 75, 63.58);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (33, 'Alfred A. Knopf', 1997, 1000, 51.06);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (34, 'Vintage Books', 2011, -1, 23.84);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (35, 'HarperCollins', 1988, 500, 66.2);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (36, 'Houghton Mifflin', 1993, 100, 37.87);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (37, 'Geoffrey Bles', 1950, 250, 67.32);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (38, 'MacAdam/Cage', 2003, 75, 60.95);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (39, 'Bantam Spectra', 1996, 25, 36.9);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (40, 'Penguin Books', 2006, 50, 68.96);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (41, 'Puffin Books', 2005, 75, 30.26);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (42, 'Roberts Brothers', 1868, 100, 71.73);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (43, 'Smith, Elder & Co.', 1847, -1, 35.27);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (44, 'Warner Books', 1996, 75, 64.3);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (45, 'Knopf Canada', 2001, 25, 35.23);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (46, 'Algonquin Books of Chapel Hill', 2006, -1, 63.33);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (47, 'Alfred A. Knopf', 2005, 1000, 57.41);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (48, 'Ballantine Books', 1953, 75, 63.58);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (49, 'Little, Brown and Company', 2006, 25, 59.31);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (50, 'Harper & Row', 1974, 250, 21.15);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (51, 'Margaret K. McElderry', 2007, 25, 57.76);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (52, 'Little, Brown and Company', 2007, 500, 21);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (53, 'Alfred A. Knopf', 2002, 50, 60.08);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (54, 'Pan Books', 1979, 250, 56.3);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (55, 'Chatto & Windus', 1932, 75, 59.03);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (56, 'Little, Brown and Company', 2008, 1000, 52.89);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (57, 'Sue Monk Kidd', 2001, 1000, 35.33);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (58, 'Chatto & Windus', 1884, -1, 53.67);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (59, 'Harper & Brothers', 1952, 25, 24.41);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (60, 'Doubleday', 2003, 50, 59.11);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (61, 'Riverhead Books', 2015, 1000, 63.8);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (62, 'Scholastic', 1995, 25, 32.05);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (63, 'Thomas Cautley Newby', 1847, 75, 37.89);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (64, 'Atria', 2004, -1, 20.17);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (65, 'Delacorte', 1969, 250, 28.01);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (66, 'Macmillan Publishers', 1936, 250, 22.49);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (67, 'Riverhead Books', 2007, 100, 68.35);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (68, 'Pocket Books', 1999, 50, 51.87);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (69, 'Katherine Tegen Books', 2012, 250, 70.39);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (70, 'Tor Books', 1985, 50, 69.03);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (71, 'Lackington, Hughes, Harding, Mavor & Jones', 1818, 25, 66.09);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (72, 'Doubleday', 1977, 1000, 42.72);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (73, 'Little, Brown and Company', 2008, 250, 50.64);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (74, 'Dutton Books', 2005, 75, 72.02);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (75, 'Picador', 1996, 100, 45.71);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (76, 'Thomas Egerton', 1811, 500, 39.81);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (77, 'Farrar, Straus and Giroux', 1998, 75, 22.61);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (78, 'Broadway Books', 2003, 50, 51.5);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (79, 'Penguin Books', -720, 50, 28.02);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (80, 'Reynal & Hitchcock', 1946, 75, 32.94);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (81, 'Scribner', 2005, 500, 54.21);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (82, 'HarperCollins', 1996, 250, 73.82);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (83, 'Chapman & Hall', 1859, 75, 20.25);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (84, 'Alfred A. Knopf', 1990, 75, 38.19);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (85, 'Harper & Row', 1964, 25, 38.44);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (86, 'Wynward Press', 1989, 1000, 68.62);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (87, 'Hill and Wang', 1958, 250, 51.03);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (88, 'Dutton Books', 2008, 1000, 46.52);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (89, 'Harcourt Brace Jovanovich', 1973, 500, 62.8);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (90, 'Viking Press', 1967, 50, 67.19);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (91, 'Delacorte Press', 2009, 1000, 73.73);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (92, 'William Morrow', 2005, 50, 59.65);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (93, 'Frederick A. Stokes', 1911, 500, 26.63);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (94, 'Harper & Row', 1967, 25, 25.17);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (95, 'Oxford University Press', 1891, 25, 51.3);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (96, 'Vintage Books', 2012, 500, 40.6);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (97, 'Archibald Constable and Company', 1897, -1, 25.19);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (98, 'Quercus', 2006, 100, 47.46);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (99, 'Vintage Books', 2011, 1000, 63.01);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (100, 'HarperCollins', 1998, 500, 41.37);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (201, 'Very Cool Publisher Inc', 2020, 100, 60.59);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (202, 'Very Cool Publisher Inc', 2020, 75, 29.65);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (203, 'Very Cool Publisher Inc', 2020, 250, 49.25);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (204, 'Very Cool Publisher Inc', 2020, 50, 66.72);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (204, 'Very Cool Publisher Inc', 2020, 250, 53.61);
INSERT INTO publishes(product_id, publisher_name, year_published, reorder_threshold, commission_percent) VALUES (205, 'Very Cool Publisher Inc', 2020, 75, 37.76);
