CREATE TABLE stored_in(product_id INT PRIMARY KEY REFERENCES book, name VARCHAR(80) NOT NULL REFERENCES warehouse, stock INT NOT NULL, aisle INT);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (1, 'Trantow, Pouros and Welch''s warehouse', 1378, 180);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (2, 'Trantow, Pouros and Welch''s warehouse', 456, 110);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (3, 'Rolfson - Cartwright''s warehouse', 1279, 125);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (4, 'Trantow, Pouros and Welch''s warehouse', 707, 136);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (5, 'Rath, Graham and Keebler''s warehouse', 787, 191);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (6, 'Rath, Graham and Keebler''s warehouse', 1910, 174);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (7, 'Rolfson - Cartwright''s warehouse', 10, 89);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (8, 'Frami - Beier''s warehouse', 1151, 166);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (9, 'Rath, Graham and Keebler''s warehouse', 2300, 248);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (10, 'Rath, Graham and Keebler''s warehouse', 419, 150);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (11, 'Rath, Graham and Keebler''s warehouse', 1884, 118);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (12, 'Johns, Hand and O''Keefe''s warehouse', 2220, 126);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (13, 'Frami - Beier''s warehouse', 1879, 110);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (14, 'Rolfson - Cartwright''s warehouse', 1357, 22);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (15, 'Trantow, Pouros and Welch''s warehouse', 1924, 128);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (16, 'Frami - Beier''s warehouse', 850, 246);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (17, 'Rolfson - Cartwright''s warehouse', 2367, 6);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (18, 'Rath, Graham and Keebler''s warehouse', 1410, 249);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (19, 'Johns, Hand and O''Keefe''s warehouse', 1186, 40);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (20, 'Trantow, Pouros and Welch''s warehouse', 984, 6);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (21, 'Rath, Graham and Keebler''s warehouse', 1192, 195);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (22, 'Rolfson - Cartwright''s warehouse', 1906, 218);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (23, 'Rath, Graham and Keebler''s warehouse', 1349, 181);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (24, 'Frami - Beier''s warehouse', 795, 219);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (25, 'Johns, Hand and O''Keefe''s warehouse', 1571, 56);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (26, 'Frami - Beier''s warehouse', 193, 105);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (27, 'Johns, Hand and O''Keefe''s warehouse', 2, 238);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (28, 'Rath, Graham and Keebler''s warehouse', 827, 120);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (29, 'Rolfson - Cartwright''s warehouse', 839, 88);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (30, 'Johns, Hand and O''Keefe''s warehouse', 752, 186);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (31, 'Johns, Hand and O''Keefe''s warehouse', 1358, 181);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (32, 'Johns, Hand and O''Keefe''s warehouse', 1645, 141);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (33, 'Trantow, Pouros and Welch''s warehouse', 901, 186);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (34, 'Johns, Hand and O''Keefe''s warehouse', 1110, 145);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (35, 'Johns, Hand and O''Keefe''s warehouse', 742, 232);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (36, 'Rath, Graham and Keebler''s warehouse', 51, 24);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (37, 'Rath, Graham and Keebler''s warehouse', 397, 178);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (38, 'Frami - Beier''s warehouse', 641, 176);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (39, 'Johns, Hand and O''Keefe''s warehouse', 129, 51);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (40, 'Frami - Beier''s warehouse', 2207, 70);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (41, 'Rolfson - Cartwright''s warehouse', 1294, 216);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (42, 'Frami - Beier''s warehouse', 2482, 190);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (43, 'Frami - Beier''s warehouse', 946, 70);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (44, 'Rolfson - Cartwright''s warehouse', 418, 90);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (45, 'Johns, Hand and O''Keefe''s warehouse', 1270, 110);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (46, 'Trantow, Pouros and Welch''s warehouse', 1136, 151);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (47, 'Trantow, Pouros and Welch''s warehouse', 1634, 137);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (48, 'Trantow, Pouros and Welch''s warehouse', 1666, 141);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (49, 'Rath, Graham and Keebler''s warehouse', 1350, 61);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (50, 'Johns, Hand and O''Keefe''s warehouse', 1641, 138);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (51, 'Frami - Beier''s warehouse', 490, 39);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (52, 'Rath, Graham and Keebler''s warehouse', 1609, 239);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (53, 'Frami - Beier''s warehouse', 694, 164);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (54, 'Johns, Hand and O''Keefe''s warehouse', 265, 29);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (55, 'Rath, Graham and Keebler''s warehouse', 1167, 105);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (56, 'Rolfson - Cartwright''s warehouse', 217, 55);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (57, 'Rolfson - Cartwright''s warehouse', 1412, 72);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (58, 'Rath, Graham and Keebler''s warehouse', 2152, 225);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (59, 'Johns, Hand and O''Keefe''s warehouse', 1890, 85);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (60, 'Frami - Beier''s warehouse', 2417, 66);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (61, 'Rath, Graham and Keebler''s warehouse', 294, 105);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (62, 'Johns, Hand and O''Keefe''s warehouse', 1323, 3);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (63, 'Rath, Graham and Keebler''s warehouse', 1081, 121);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (64, 'Rath, Graham and Keebler''s warehouse', 491, 175);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (65, 'Johns, Hand and O''Keefe''s warehouse', 983, 186);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (66, 'Frami - Beier''s warehouse', 2055, 74);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (67, 'Rolfson - Cartwright''s warehouse', 1550, 79);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (68, 'Johns, Hand and O''Keefe''s warehouse', 1897, 150);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (69, 'Rath, Graham and Keebler''s warehouse', 459, 215);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (70, 'Rolfson - Cartwright''s warehouse', 959, 173);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (71, 'Johns, Hand and O''Keefe''s warehouse', 606, 44);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (72, 'Frami - Beier''s warehouse', 879, 170);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (73, 'Trantow, Pouros and Welch''s warehouse', 625, 220);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (74, 'Johns, Hand and O''Keefe''s warehouse', 31, 215);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (75, 'Johns, Hand and O''Keefe''s warehouse', 1203, 59);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (76, 'Rath, Graham and Keebler''s warehouse', 598, 202);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (77, 'Frami - Beier''s warehouse', 2109, 20);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (78, 'Johns, Hand and O''Keefe''s warehouse', 2014, 100);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (79, 'Frami - Beier''s warehouse', 1996, 16);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (80, 'Frami - Beier''s warehouse', 2155, 248);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (81, 'Johns, Hand and O''Keefe''s warehouse', 1261, 39);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (82, 'Rath, Graham and Keebler''s warehouse', 233, 96);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (83, 'Frami - Beier''s warehouse', 2347, 173);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (84, 'Rath, Graham and Keebler''s warehouse', 1265, 18);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (85, 'Rath, Graham and Keebler''s warehouse', 988, 89);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (86, 'Trantow, Pouros and Welch''s warehouse', 714, 182);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (87, 'Trantow, Pouros and Welch''s warehouse', 143, 148);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (88, 'Trantow, Pouros and Welch''s warehouse', 1992, 189);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (89, 'Trantow, Pouros and Welch''s warehouse', 1400, 83);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (90, 'Johns, Hand and O''Keefe''s warehouse', 2154, 47);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (91, 'Rath, Graham and Keebler''s warehouse', 221, 59);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (92, 'Rolfson - Cartwright''s warehouse', 554, 153);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (93, 'Johns, Hand and O''Keefe''s warehouse', 2336, 203);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (94, 'Johns, Hand and O''Keefe''s warehouse', 1750, 73);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (95, 'Rath, Graham and Keebler''s warehouse', 288, 24);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (96, 'Frami - Beier''s warehouse', 772, 57);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (97, 'Trantow, Pouros and Welch''s warehouse', 1975, 192);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (98, 'Trantow, Pouros and Welch''s warehouse', 1359, 131);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (99, 'Frami - Beier''s warehouse', 870, 98);
INSERT INTO stored_in(product_id, name, stock, aisle) VALUES (100, 'Rolfson - Cartwright''s warehouse', 2432, 229);
