CREATE TABLE stored_in(product_id INT PRIMARY KEY, warehouse_name VARCHAR(80) NOT NULL REFERENCES warehouse, stock INT NOT NULL, aisle INT);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (1, 'Trantow, Pouros and Welch''s warehouse', 1378, 180);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (2, 'Johns, Hand and O''Keefe''s warehouse', 69, 108);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (3, 'Johns, Hand and O''Keefe''s warehouse', 1431, 53);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (4, 'Rath, Graham and Keebler''s warehouse', 731, 100);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (5, 'Rolfson - Cartwright''s warehouse', 739, 246);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (6, 'Trantow, Pouros and Welch''s warehouse', 766, 249);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (7, 'Johns, Hand and O''Keefe''s warehouse', 2173, 141);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (8, 'Johns, Hand and O''Keefe''s warehouse', 1653, 245);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (9, 'Johns, Hand and O''Keefe''s warehouse', 591, 43);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (10, 'Trantow, Pouros and Welch''s warehouse', 1491, 52);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (11, 'Frami - Beier''s warehouse', 806, 53);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (12, 'Frami - Beier''s warehouse', 1149, 233);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (13, 'Frami - Beier''s warehouse', 1202, 223);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (14, 'Johns, Hand and O''Keefe''s warehouse', 1358, 181);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (15, 'Rath, Graham and Keebler''s warehouse', 1867, 126);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (16, 'Frami - Beier''s warehouse', 1173, 41);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (17, 'Trantow, Pouros and Welch''s warehouse', 2358, 1);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (18, 'Rolfson - Cartwright''s warehouse', 2312, 99);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (19, 'Frami - Beier''s warehouse', 874, 160);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (20, 'Johns, Hand and O''Keefe''s warehouse', 96, 94);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (21, 'Rath, Graham and Keebler''s warehouse', 1832, 229);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (22, 'Rolfson - Cartwright''s warehouse', 718, 62);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (23, 'Johns, Hand and O''Keefe''s warehouse', 532, 46);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (24, 'Rolfson - Cartwright''s warehouse', 1241, 247);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (25, 'Rolfson - Cartwright''s warehouse', 2010, 102);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (26, 'Trantow, Pouros and Welch''s warehouse', 1488, 169);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (27, 'Rolfson - Cartwright''s warehouse', 147, 227);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (28, 'Rath, Graham and Keebler''s warehouse', 1818, 7);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (29, 'Rolfson - Cartwright''s warehouse', 87, 71);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (30, 'Johns, Hand and O''Keefe''s warehouse', 2192, 120);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (31, 'Frami - Beier''s warehouse', 1296, 89);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (32, 'Trantow, Pouros and Welch''s warehouse', 2026, 124);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (33, 'Rath, Graham and Keebler''s warehouse', 2263, 97);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (34, 'Rath, Graham and Keebler''s warehouse', 2152, 225);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (35, 'Rath, Graham and Keebler''s warehouse', 1253, 3);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (36, 'Frami - Beier''s warehouse', 2470, 41);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (37, 'Frami - Beier''s warehouse', 877, 248);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (38, 'Rath, Graham and Keebler''s warehouse', 624, 247);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (39, 'Frami - Beier''s warehouse', 2055, 74);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (40, 'Trantow, Pouros and Welch''s warehouse', 1395, 155);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (41, 'Rath, Graham and Keebler''s warehouse', 281, 169);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (42, 'Rath, Graham and Keebler''s warehouse', 2057, 7);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (43, 'Rolfson - Cartwright''s warehouse', 1908, 87);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (44, 'Frami - Beier''s warehouse', 1032, 1);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (45, 'Johns, Hand and O''Keefe''s warehouse', 1221, 219);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (46, 'Frami - Beier''s warehouse', 890, 63);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (47, 'Rath, Graham and Keebler''s warehouse', 1030, 46);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (48, 'Rolfson - Cartwright''s warehouse', 120, 157);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (49, 'Johns, Hand and O''Keefe''s warehouse', 1677, 180);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (50, 'Johns, Hand and O''Keefe''s warehouse', 1082, 105);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (51, 'Rolfson - Cartwright''s warehouse', 519, 106);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (52, 'Frami - Beier''s warehouse', 686, 41);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (53, 'Frami - Beier''s warehouse', 1655, 178);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (54, 'Trantow, Pouros and Welch''s warehouse', 143, 148);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (55, 'Trantow, Pouros and Welch''s warehouse', 1775, 59);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (56, 'Frami - Beier''s warehouse', 230, 191);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (57, 'Rath, Graham and Keebler''s warehouse', 2079, 121);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (58, 'Johns, Hand and O''Keefe''s warehouse', 2336, 203);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (59, 'Rath, Graham and Keebler''s warehouse', 281, 28);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (60, 'Rolfson - Cartwright''s warehouse', 349, 240);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (61, 'Frami - Beier''s warehouse', 981, 103);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (62, 'Rolfson - Cartwright''s warehouse', 1239, 231);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (63, 'Trantow, Pouros and Welch''s warehouse', 1770, 162);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (64, 'Rolfson - Cartwright''s warehouse', 497, 127);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (65, 'Johns, Hand and O''Keefe''s warehouse', 841, 137);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (66, 'Trantow, Pouros and Welch''s warehouse', 2141, 217);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (67, 'Frami - Beier''s warehouse', 1431, 3);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (68, 'Johns, Hand and O''Keefe''s warehouse', 2427, 30);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (69, 'Frami - Beier''s warehouse', 752, 107);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (70, 'Johns, Hand and O''Keefe''s warehouse', 1364, 128);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (71, 'Frami - Beier''s warehouse', 1083, 217);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (72, 'Frami - Beier''s warehouse', 1009, 185);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (73, 'Trantow, Pouros and Welch''s warehouse', 2088, 51);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (74, 'Trantow, Pouros and Welch''s warehouse', 249, 210);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (75, 'Frami - Beier''s warehouse', 407, 217);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (76, 'Rolfson - Cartwright''s warehouse', 1100, 6);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (77, 'Johns, Hand and O''Keefe''s warehouse', 815, 166);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (78, 'Rolfson - Cartwright''s warehouse', 1432, 121);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (79, 'Rolfson - Cartwright''s warehouse', 370, 228);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (80, 'Trantow, Pouros and Welch''s warehouse', 1042, 241);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (81, 'Frami - Beier''s warehouse', 159, 208);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (82, 'Rolfson - Cartwright''s warehouse', 963, 45);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (83, 'Johns, Hand and O''Keefe''s warehouse', 2385, 94);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (84, 'Rolfson - Cartwright''s warehouse', 1729, 27);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (85, 'Rath, Graham and Keebler''s warehouse', 2143, 223);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (86, 'Johns, Hand and O''Keefe''s warehouse', 1085, 74);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (87, 'Trantow, Pouros and Welch''s warehouse', 209, 133);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (88, 'Trantow, Pouros and Welch''s warehouse', 1808, 153);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (89, 'Johns, Hand and O''Keefe''s warehouse', 1641, 245);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (90, 'Rolfson - Cartwright''s warehouse', 1081, 158);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (91, 'Johns, Hand and O''Keefe''s warehouse', 2204, 226);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (92, 'Frami - Beier''s warehouse', 2226, 244);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (93, 'Rolfson - Cartwright''s warehouse', 2439, 250);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (94, 'Johns, Hand and O''Keefe''s warehouse', 798, 5);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (95, 'Rath, Graham and Keebler''s warehouse', 1058, 51);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (96, 'Trantow, Pouros and Welch''s warehouse', 1528, 52);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (97, 'Rath, Graham and Keebler''s warehouse', 155, 249);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (98, 'Johns, Hand and O''Keefe''s warehouse', 604, 151);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (99, 'Rath, Graham and Keebler''s warehouse', 1441, 86);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (100, 'Rolfson - Cartwright''s warehouse', 1828, 40);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (201, 'Trantow, Pouros and Welch''s warehouse', 6, 99);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (202, 'Trantow, Pouros and Welch''s warehouse', 4998, 45);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (203, 'Rath, Graham and Keebler''s warehouse', 4997, 133);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (204, 'Johns, Hand and O''Keefe''s warehouse', 4996, 159);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (205, 'Johns, Hand and O''Keefe''s warehouse', 4995, 181);
INSERT INTO stored_in(product_id, warehouse_name, stock, aisle) VALUES (206, 'Frami - Beier''s warehouse', 4994, 181);
