CREATE TABLE writes(product_id INT NOT NULL REFERENCES book, author_name VARCHAR(80) NOT NULL REFERENCES author(name), PRIMARY KEY(product_id, author_name));
INSERT INTO writes(product_id, author_name) VALUES (1, 'Suzanne Collins') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (2, 'J.K. Rowling') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (2, 'Mary GrandPré') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (3, 'Stephenie Meyer') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (4, 'Harper Lee') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (5, 'F. Scott Fitzgerald') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (6, 'John Green') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (7, 'J.R.R. Tolkien') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (8, 'J.D. Salinger') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (9, 'Dan Brown') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (10, 'Jane Austen') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (11, 'Khaled Hosseini') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (12, 'Veronica Roth') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (13, 'George Orwell') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (13, 'Erich Fromm') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (13, 'Celâl Üster') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (14, 'George Orwell') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (15, 'Anne Frank') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (15, 'Eleanor Roosevelt') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (15, 'B.M. Mooyaart-Doubleday') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (16, 'Stieg Larsson') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (16, 'Reg Keeland') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (17, 'Suzanne Collins') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (18, 'J.K. Rowling') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (18, 'Mary GrandPré') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (18, 'Rufus Beck') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (19, 'J.R.R. Tolkien') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (20, 'Suzanne Collins') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (21, 'J.K. Rowling') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (21, 'Mary GrandPré') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (22, 'Alice Sebold') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (23, 'J.K. Rowling') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (23, 'Mary GrandPré') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (24, 'J.K. Rowling') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (24, 'Mary GrandPré') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (25, 'J.K. Rowling') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (25, 'Mary GrandPré') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (26, 'Dan Brown') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (27, 'J.K. Rowling') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (27, 'Mary GrandPré') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (28, 'William Golding') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (29, 'William Shakespeare') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (29, 'Robert           Jackson') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (30, 'Gillian Flynn') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (31, 'Kathryn Stockett') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (32, 'John Steinbeck') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (33, 'Arthur Golden') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (34, 'E.L. James') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (35, 'Paulo Coelho') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (35, 'Alan R. Clarke') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (36, 'Lois Lowry') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (37, 'C.S. Lewis') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (38, 'Audrey Niffenegger') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (39, 'George R.R. Martin') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (40, 'Elizabeth Gilbert') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (41, 'Rick Riordan') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (42, 'Louisa May Alcott') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (43, 'Charlotte Brontë') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (43, 'Michael Mason') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (44, 'Nicholas Sparks') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (45, 'Yann Martel') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (46, 'Sara Gruen') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (47, 'Markus Zusak') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (48, 'Ray Bradbury') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (49, 'Stephenie Meyer') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (50, 'Shel Silverstein') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (51, 'Cassandra Clare') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (52, 'Stephenie Meyer') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (53, 'Christopher Paolini') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (54, 'Douglas Adams') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (55, 'Aldous Huxley') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (56, 'Stephenie Meyer') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (57, 'Sue Monk Kidd') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (58, 'Mark Twain') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (58, 'John Seelye') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (58, 'Guy Cardwell') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (59, 'E.B. White') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (59, 'Garth Williams') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (59, 'Rosemary Wells') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (60, 'Mark Haddon') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (61, 'Paula Hawkins') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (62, 'Philip Pullman') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (63, 'Emily Brontë') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (63, 'Richard J. Dunn') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (64, 'Jodi Picoult') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (65, 'Kurt Vonnegut Jr.') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (66, 'Margaret Mitchell') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (67, 'Khaled Hosseini') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (68, 'Stephen Chbosky') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (69, 'Veronica Roth') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (70, 'Orson Scott Card') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (71, 'Mary Wollstonecraft Shelley') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (71, 'Percy Bysshe Shelley') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (71, 'Maurice Hindle') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (72, 'Stephen King') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (73, 'Stephenie Meyer') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (74, 'John Green') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (75, 'Helen Fielding') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (76, 'Jane Austen') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (76, 'Tony Tanner') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (76, 'Ros Ballaster') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (77, 'Louis Sachar') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (77, 'Louis Sachar') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (78, 'Lauren Weisberger') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (79, 'Homer') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (79, 'Robert Fagles') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (79, 'E.V. Rieu') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (79, 'Frédéric Mugler') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (79, 'Bernard Knox') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (80, 'Antoine de Saint-Exupéry') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (80, 'Richard Howard') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (80, 'Dom Marcos Barbosa') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (80, 'Melina Karakosta') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (81, 'Jeannette Walls') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (82, 'Jon Krakauer') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (83, 'Charles Dickens') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (83, 'Richard Maxwell') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (83, 'Hablot Knight Browne') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (84, 'Michael Crichton') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (85, 'Shel Silverstein') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (86, 'John Grisham') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (87, 'Elie Wiesel') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (87, 'Marion Wiesel') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (88, 'John Green') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (89, 'William Goldman') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (90, 'S.E. Hinton') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (91, 'James Dashner') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (92, 'Steven D. Levitt') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (92, 'Stephen J. Dubner') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (93, 'Frances Hodgson Burnett') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (94, 'Gabriel García Márquez') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (94, 'Gregory Rabassa') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (95, 'Oscar Wilde') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (95, 'Jeffrey Eugenides') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (96, 'E.L. James') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (97, 'Bram Stoker') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (97, 'Nina Auerbach') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (97, 'David J. Skal') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (98, 'Stieg Larsson') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (98, 'Reg Keeland') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (99, 'E.L. James') ON CONFLICT DO NOTHING;
INSERT INTO writes(product_id, author_name) VALUES (100, 'Barbara Kingsolver') ON CONFLICT DO NOTHING;
