CREATE TABLE author(name VARCHAR(80) PRIMARY KEY, picture BLOB, summary VARCHAR(2047));
INSERT INTO writes(product_id, name) VALUES (1, 'Suzanne Collins');
INSERT INTO writes(product_id, name) VALUES (2, 'J.K. Rowling');
INSERT INTO writes(product_id, name) VALUES (2, 'Mary GrandPré');
INSERT INTO writes(product_id, name) VALUES (3, 'Stephenie Meyer');
INSERT INTO writes(product_id, name) VALUES (4, 'Harper Lee');
INSERT INTO writes(product_id, name) VALUES (5, 'F. Scott Fitzgerald');
INSERT INTO writes(product_id, name) VALUES (6, 'John Green');
INSERT INTO writes(product_id, name) VALUES (7, 'J.R.R. Tolkien');
INSERT INTO writes(product_id, name) VALUES (8, 'J.D. Salinger');
INSERT INTO writes(product_id, name) VALUES (9, 'Dan Brown');
INSERT INTO writes(product_id, name) VALUES (10, 'Jane Austen');
INSERT INTO writes(product_id, name) VALUES (11, 'Khaled Hosseini');
INSERT INTO writes(product_id, name) VALUES (12, 'Veronica Roth');
INSERT INTO writes(product_id, name) VALUES (13, 'George Orwell');
INSERT INTO writes(product_id, name) VALUES (13, 'Erich Fromm');
INSERT INTO writes(product_id, name) VALUES (13, 'Celâl Üster');
INSERT INTO writes(product_id, name) VALUES (14, 'George Orwell');
INSERT INTO writes(product_id, name) VALUES (15, 'Anne Frank');
INSERT INTO writes(product_id, name) VALUES (15, 'Eleanor Roosevelt');
INSERT INTO writes(product_id, name) VALUES (15, 'B.M. Mooyaart-Doubleday');
INSERT INTO writes(product_id, name) VALUES (16, 'Stieg Larsson');
INSERT INTO writes(product_id, name) VALUES (16, 'Reg Keeland');
INSERT INTO writes(product_id, name) VALUES (17, 'Suzanne Collins');
INSERT INTO writes(product_id, name) VALUES (18, 'J.K. Rowling');
INSERT INTO writes(product_id, name) VALUES (18, 'Mary GrandPré');
INSERT INTO writes(product_id, name) VALUES (18, 'Rufus Beck');
INSERT INTO writes(product_id, name) VALUES (19, 'J.R.R. Tolkien');
INSERT INTO writes(product_id, name) VALUES (20, 'Suzanne Collins');
INSERT INTO writes(product_id, name) VALUES (21, 'J.K. Rowling');
INSERT INTO writes(product_id, name) VALUES (21, 'Mary GrandPré');
INSERT INTO writes(product_id, name) VALUES (22, 'Alice Sebold');
INSERT INTO writes(product_id, name) VALUES (23, 'J.K. Rowling');
INSERT INTO writes(product_id, name) VALUES (23, 'Mary GrandPré');
INSERT INTO writes(product_id, name) VALUES (24, 'J.K. Rowling');
INSERT INTO writes(product_id, name) VALUES (24, 'Mary GrandPré');
INSERT INTO writes(product_id, name) VALUES (25, 'J.K. Rowling');
INSERT INTO writes(product_id, name) VALUES (25, 'Mary GrandPré');
INSERT INTO writes(product_id, name) VALUES (26, 'Dan Brown');
INSERT INTO writes(product_id, name) VALUES (27, 'J.K. Rowling');
INSERT INTO writes(product_id, name) VALUES (27, 'Mary GrandPré');
INSERT INTO writes(product_id, name) VALUES (28, 'William Golding');
INSERT INTO writes(product_id, name) VALUES (29, 'William Shakespeare');
INSERT INTO writes(product_id, name) VALUES (29, 'Robert           Jackson');
INSERT INTO writes(product_id, name) VALUES (30, 'Gillian Flynn');
INSERT INTO writes(product_id, name) VALUES (31, 'Kathryn Stockett');
INSERT INTO writes(product_id, name) VALUES (32, 'John Steinbeck');
INSERT INTO writes(product_id, name) VALUES (33, 'Arthur Golden');
INSERT INTO writes(product_id, name) VALUES (34, 'E.L. James');
INSERT INTO writes(product_id, name) VALUES (35, 'Paulo Coelho');
INSERT INTO writes(product_id, name) VALUES (35, 'Alan R. Clarke');
INSERT INTO writes(product_id, name) VALUES (36, 'Lois Lowry');
INSERT INTO writes(product_id, name) VALUES (37, 'C.S. Lewis');
INSERT INTO writes(product_id, name) VALUES (38, 'Audrey Niffenegger');
INSERT INTO writes(product_id, name) VALUES (39, 'George R.R. Martin');
INSERT INTO writes(product_id, name) VALUES (40, 'Elizabeth Gilbert');
INSERT INTO writes(product_id, name) VALUES (41, 'Rick Riordan');
INSERT INTO writes(product_id, name) VALUES (42, 'Louisa May Alcott');
INSERT INTO writes(product_id, name) VALUES (43, 'Charlotte Brontë');
INSERT INTO writes(product_id, name) VALUES (43, 'Michael Mason');
INSERT INTO writes(product_id, name) VALUES (44, 'Nicholas Sparks');
INSERT INTO writes(product_id, name) VALUES (45, 'Yann Martel');
INSERT INTO writes(product_id, name) VALUES (46, 'Sara Gruen');
INSERT INTO writes(product_id, name) VALUES (47, 'Markus Zusak');
INSERT INTO writes(product_id, name) VALUES (48, 'Ray Bradbury');
INSERT INTO writes(product_id, name) VALUES (49, 'Stephenie Meyer');
INSERT INTO writes(product_id, name) VALUES (50, 'Shel Silverstein');
INSERT INTO writes(product_id, name) VALUES (51, 'Cassandra Clare');
INSERT INTO writes(product_id, name) VALUES (52, 'Stephenie Meyer');
INSERT INTO writes(product_id, name) VALUES (53, 'Christopher Paolini');
INSERT INTO writes(product_id, name) VALUES (54, 'Douglas Adams');
INSERT INTO writes(product_id, name) VALUES (55, 'Aldous Huxley');
INSERT INTO writes(product_id, name) VALUES (56, 'Stephenie Meyer');
INSERT INTO writes(product_id, name) VALUES (57, 'Sue Monk Kidd');
INSERT INTO writes(product_id, name) VALUES (58, 'Mark Twain');
INSERT INTO writes(product_id, name) VALUES (58, 'John Seelye');
INSERT INTO writes(product_id, name) VALUES (58, 'Guy Cardwell');
INSERT INTO writes(product_id, name) VALUES (59, 'E.B. White');
INSERT INTO writes(product_id, name) VALUES (59, 'Garth Williams');
INSERT INTO writes(product_id, name) VALUES (59, 'Rosemary Wells');
INSERT INTO writes(product_id, name) VALUES (60, 'Mark Haddon');
INSERT INTO writes(product_id, name) VALUES (61, 'Paula Hawkins');
INSERT INTO writes(product_id, name) VALUES (62, 'Philip Pullman');
INSERT INTO writes(product_id, name) VALUES (63, 'Emily Brontë');
INSERT INTO writes(product_id, name) VALUES (63, 'Richard J. Dunn');
INSERT INTO writes(product_id, name) VALUES (64, 'Jodi Picoult');
INSERT INTO writes(product_id, name) VALUES (65, 'Kurt Vonnegut Jr.');
INSERT INTO writes(product_id, name) VALUES (66, 'Margaret Mitchell');
INSERT INTO writes(product_id, name) VALUES (67, 'Khaled Hosseini');
INSERT INTO writes(product_id, name) VALUES (68, 'Stephen Chbosky');
INSERT INTO writes(product_id, name) VALUES (69, 'Veronica Roth');
INSERT INTO writes(product_id, name) VALUES (70, 'Orson Scott Card');
INSERT INTO writes(product_id, name) VALUES (71, 'Mary Wollstonecraft Shelley');
INSERT INTO writes(product_id, name) VALUES (71, 'Percy Bysshe Shelley');
INSERT INTO writes(product_id, name) VALUES (71, 'Maurice Hindle');
INSERT INTO writes(product_id, name) VALUES (72, 'Stephen King');
INSERT INTO writes(product_id, name) VALUES (73, 'Stephenie Meyer');
INSERT INTO writes(product_id, name) VALUES (74, 'John Green');
INSERT INTO writes(product_id, name) VALUES (75, 'Helen Fielding');
INSERT INTO writes(product_id, name) VALUES (76, 'Jane Austen');
INSERT INTO writes(product_id, name) VALUES (76, 'Tony Tanner');
INSERT INTO writes(product_id, name) VALUES (76, 'Ros Ballaster');
INSERT INTO writes(product_id, name) VALUES (77, 'Louis Sachar');
INSERT INTO writes(product_id, name) VALUES (77, 'Louis Sachar');
INSERT INTO writes(product_id, name) VALUES (78, 'Lauren Weisberger');
INSERT INTO writes(product_id, name) VALUES (79, 'Homer');
INSERT INTO writes(product_id, name) VALUES (79, 'Robert Fagles');
INSERT INTO writes(product_id, name) VALUES (79, 'E.V. Rieu');
INSERT INTO writes(product_id, name) VALUES (79, 'Frédéric Mugler');
INSERT INTO writes(product_id, name) VALUES (79, 'Bernard Knox');
INSERT INTO writes(product_id, name) VALUES (80, 'Antoine de Saint-Exupéry');
INSERT INTO writes(product_id, name) VALUES (80, 'Richard Howard');
INSERT INTO writes(product_id, name) VALUES (80, 'Dom Marcos Barbosa');
INSERT INTO writes(product_id, name) VALUES (80, 'Melina Karakosta');
INSERT INTO writes(product_id, name) VALUES (81, 'Jeannette Walls');
INSERT INTO writes(product_id, name) VALUES (82, 'Jon Krakauer');
INSERT INTO writes(product_id, name) VALUES (83, 'Charles Dickens');
INSERT INTO writes(product_id, name) VALUES (83, 'Richard Maxwell');
INSERT INTO writes(product_id, name) VALUES (83, 'Hablot Knight Browne');
INSERT INTO writes(product_id, name) VALUES (84, 'Michael Crichton');
INSERT INTO writes(product_id, name) VALUES (85, 'Shel Silverstein');
INSERT INTO writes(product_id, name) VALUES (86, 'John Grisham');
INSERT INTO writes(product_id, name) VALUES (87, 'Elie Wiesel');
INSERT INTO writes(product_id, name) VALUES (87, 'Marion Wiesel');
INSERT INTO writes(product_id, name) VALUES (88, 'John Green');
INSERT INTO writes(product_id, name) VALUES (89, 'William Goldman');
INSERT INTO writes(product_id, name) VALUES (90, 'S.E. Hinton');
INSERT INTO writes(product_id, name) VALUES (91, 'James Dashner');
INSERT INTO writes(product_id, name) VALUES (92, 'Steven D. Levitt');
INSERT INTO writes(product_id, name) VALUES (92, 'Stephen J. Dubner');
INSERT INTO writes(product_id, name) VALUES (93, 'Frances Hodgson Burnett');
INSERT INTO writes(product_id, name) VALUES (94, 'Gabriel García Márquez');
INSERT INTO writes(product_id, name) VALUES (94, 'Gregory Rabassa');
INSERT INTO writes(product_id, name) VALUES (95, 'Oscar Wilde');
INSERT INTO writes(product_id, name) VALUES (95, 'Jeffrey Eugenides');
INSERT INTO writes(product_id, name) VALUES (96, 'E.L. James');
INSERT INTO writes(product_id, name) VALUES (97, 'Bram Stoker');
INSERT INTO writes(product_id, name) VALUES (97, 'Nina Auerbach');
INSERT INTO writes(product_id, name) VALUES (97, 'David J. Skal');
INSERT INTO writes(product_id, name) VALUES (98, 'Stieg Larsson');
INSERT INTO writes(product_id, name) VALUES (98, 'Reg Keeland');
INSERT INTO writes(product_id, name) VALUES (99, 'E.L. James');
INSERT INTO writes(product_id, name) VALUES (100, 'Barbara Kingsolver');
